version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - ming-tsai
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.41.2
    - 2.43.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
    - 7.13.8
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.0
